// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANc1eNrq2hld5TCVMMrGVkEjp33xpKbfI',
    appId: '1:389224186267:web:4f8e478340686abf82e13e',
    messagingSenderId: '389224186267',
    projectId: 'medplus3125',
    authDomain: 'medplus3125.firebaseapp.com',
    storageBucket: 'medplus3125.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMOdideo10WzT_twpSSGfeVclUEEQC9E',
    appId: '1:389224186267:android:c847ae952d25587482e13e',
    messagingSenderId: '389224186267',
    projectId: 'medplus3125',
    storageBucket: 'medplus3125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-NQdza3q4-WbKzNcbKAYfQU7Ad6EthNI',
    appId: '1:389224186267:ios:7d177224a065c65082e13e',
    messagingSenderId: '389224186267',
    projectId: 'medplus3125',
    storageBucket: 'medplus3125.firebasestorage.app',
    iosBundleId: 'com.example.cardiovascularWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-NQdza3q4-WbKzNcbKAYfQU7Ad6EthNI',
    appId: '1:389224186267:ios:7d177224a065c65082e13e',
    messagingSenderId: '389224186267',
    projectId: 'medplus3125',
    storageBucket: 'medplus3125.firebasestorage.app',
    iosBundleId: 'com.example.cardiovascularWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANc1eNrq2hld5TCVMMrGVkEjp33xpKbfI',
    appId: '1:389224186267:web:d7cfd74899407abf82e13e',
    messagingSenderId: '389224186267',
    projectId: 'medplus3125',
    authDomain: 'medplus3125.firebaseapp.com',
    storageBucket: 'medplus3125.firebasestorage.app',
  );
}
